server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ =404;
    }

    # Habilitar compresión Gzip para mejorar rendimiento de carga
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Configuración de caché óptima para imágenes y recursos estáticos
    location ~* \.(?:jpg|jpeg|gif|png|ico|svg|webp)$ {
        root /usr/share/nginx/html;
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }
}
